embedding_model:
  provider: "HuggingFace"
  name: "model/sentence-transformers/all-MiniLM-L6-v2"

llm:
  HuggingFace:
    provider: "HuggingFace"
    name: "model/gpt2"
    temperature: 0.7
    max_length: 1000
    top_p: 0.9
    top_k: 50
  openai:
    provider: "OpenAI"
    model_name: "gpt-4o"
    temperature: 0.7
    max_length: 1000
    top_p: 0.9
    top_k: 50